export enum ChatEvents {
    Validate = 'validate',
    ValidateACK = 'validateWithAck',
    BroadcastAll = 'broadcastAll',
    JoinRoom = 'joinRoom',
    RoomMessage = 'roomMessage',
    Broadcast = 'broadcast',
    WordValidated = 'wordValidated',
    MassMessage = 'massMessage',
    Hello = 'hello',
    Clock = 'clock',
    Create = 'create',
    LeaveRoom = 'leaveRoom',
    DeleteRoom = 'deleteRoom',
    AddToWaitingLine = 'addToWaitingLine',
    RemoveFromWaitingLine = 'removeFromWaitingLine',
}
